version: '3.8'

services:
  mysqldb:
    container_name: attendance_mysqldb
    image: registry.hub.docker.com/library/mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=attendance
    ports:
      - "3306:3306"
    volumes:
      - attendance_mysqldb:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build:
      context: .
    container_name: attendance
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      DATABASE_URL: jdbc:mysql://attendance_mysqldb:3306/attendance?allowPublicKeyRetrieval=true&serverTimezone=UTC&useSSL=false
      DATABASE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: 1234
      HIBERNATE_DDL_POLICY: update
      HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
      AUTH_COOKIE_NAME: JWT-token
      AUTH_JWT_SECRET: 123456
      AUTH_PBKDF2_SECRET: 456789
      SPRING_APPLICATION_JSON: '{
        "spring.jpa.show-sql" : true,
        "logging.level.org.hibernate.SQL" : "debug",   
        "server.port" : "80"
      }'
    volumes:
      - attendance_mysqldb:/root/.m2
    stdin_open: true
    tty: true

volumes:
  attendance_mysqldb: